Added: getting a activity and deleting activity
alkemyTech/OT124-SERVER pull request #54
Opened 2022-02-08 22:57 UTC by panchoarc

### Summary

## Added

- Controller and routes for getting a activity and deleting a activity.

2022-02-08 23:02 UTC, FrancoMartinPersonal approved these changes

2022-02-09 19:09 UTC, rafalynch requested changes
Pancho, faltaria agregarle la función para que borre la foto de AWS en el delete y para que en el get devuelva la key del archivo (y no la url completa), parseando la url con el helper correspondiente.

2022-02-09 22:20 UTC, panchoarc commented
Arreglados los conflictos y las sugerencias dadas con respecto a los archivos a espera de permisos.

2022-02-10 12:48 UTC, dhsosa98 commented on src/controllers/activities.js
> +        await deleteFile(key, next);
Pancho, acá mientras solo comenta la línea hasta que nos avisen si vamos a poder borrar o no los files del bucket

2022-02-10 12:49 UTC, dhsosa98 commented on src/controllers/activities.js
> +        await deleteFile(key, next);
Pancho, acá mientras solo comenta la línea hasta que nos avisen si vamos a poder borrar o no los files del bucket

2022-02-11 21:09 UTC, panchoarc commented on src/controllers/activities.js
> +        await deleteFile(key, next);
Lo que pasa, es que por ahora y según requerimiento, no debo enviar una imagen, entonces por eso está puesto, además que es necesario para poder avanzar con mis otras tareas.

2022-02-11 21:31 UTC, necogamy approved these changes

2022-02-13 05:14 UTC, merged