Back organization
alkemyTech/OT124-SERVER pull request #76
Opened 2022-02-20 09:09 UTC by FrancoMartinPersonal

2022-02-20 10:33 UTC, dhsosa98 approved these changes

2022-02-22 20:00 UTC, rafalynch requested changes
Franquito, te dejo unas mínimas sugerencias!

2022-02-22 20:00 UTC, rafalynch commented on src/controllers/organizations.js
> +    console.log(err)
```suggestion
    next(err)
```

2022-02-22 20:00 UTC, rafalynch commented on src/controllers/organizations.js
> +    console.log(req.body)
```suggestion

```

2022-02-22 20:00 UTC, rafalynch commented on src/controllers/organizations.js
> +    console.log(data)
```suggestion

```

2022-02-22 20:00 UTC, rafalynch commented on src/controllers/organizations.js
> +    console.log(organizationFounded)
```suggestion

```

2022-02-22 21:28 UTC, juanpa0011 approved these changes

2022-02-22 21:28 UTC, panchoarc approved these changes

2022-02-22 21:28 UTC, merged