News seeder
alkemyTech/OT124-SERVER pull request #83
Opened 2022-02-23 18:59 UTC by juanpa0011

2022-02-23 20:26 UTC, rafalynch requested changes
JP, faltaría agregar en memberSchema las constantes FILE_SIZE y SUPPORTED_FORMATS para la validación del archivo.
Para el seed, te deje algunas sugerencias. Ademas algo importante es que el archivo deberia llegar como un parsedS3File, es decir como minimo con una key para poder renderizarlo en el front.

2022-02-23 20:26 UTC, rafalynch commented on src/seeders/20220223185051-demo-news.js
> +    return queryInterface.bulkInsert("Users", [
```suggestion
    return queryInterface.bulkInsert("News", [
```

2022-02-23 20:26 UTC, rafalynch commented on src/seeders/20220223185051-demo-news.js
> +    const general = await generateEncryptedPassword("123456")
```suggestion

```

2022-02-23 20:26 UTC, rafalynch commented on src/seeders/20220223185051-demo-news.js
> +  async up (queryInterface, Sequelize) {
```suggestion
  async up (queryInterface) {
```

2022-02-25 19:29 UTC, rafalynch approved these changes

2022-02-25 19:31 UTC, rafalynch requested changes
JP, ojo que te quedaron el controllers/members unas lineas que tienen que ver con el merge.

2022-02-25 21:44 UTC, panchoarc commented
Me sumo al comentario de rafa, algunos de los merge en members, quedaron en el archivo.
Haciendo eso yo creo que estaría listo para aprobar.

2022-02-25 22:03 UTC, rafalynch approved these changes

2022-02-25 22:06 UTC, panchoarc approved these changes

2022-02-25 22:07 UTC, merged